### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by junorouse** [nerogit/slideshare-downloader#4]
- [ ] 모바일지원
- [x] 아.. 졸리다..
- [ ] 마ㅣ일스톤에 넣어주세요
- [ ] 라벨도 붙여주세염..
- [x] 으아아아아아아아아아아아아아앙아아아아아아앙아아악 슬라이드쉐어가 안들어가짐
- [x] 왜지...?

**Comment by nerogit** [comment]
직접하시죠

**Comment by nerogit** [comment]
전 졸업해서...ㅎ

**Comment by junorouse** [comment]
@nerogit ㅇㅋ
